apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wekan-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/schnell18/play-gitops.git
    targetRevision: HEAD
    path: wekan
  destination:
    server: https://kubernetes.default.svc
    namespace: kanban

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
